### ISSUE TITLE
Bugs: Col组件结束标记没有正确识别

### ISSUE THREAD

**Issue by TimChen44** [ant-design-blazor/ant-design-blazor#225] opened 2020-06-15 05:24 UTC
![image](https://user-images.githubusercontent.com/7581981/84620692-3bbd8a80-af0b-11ea-9cc3-71af7e795d62.png)

Col组件结束标记没有正确识别，IDE提示语法错误，但是可以正常运行。

**Comment by kwinkel** [comment] 2020-06-29 20:45
@ElderJames, this bug prevents using components with scopes. Sample:
```
@if (SomeCondition == null)
{
    <Row>
        <Col>        
            <Text>Test</Text>
        </Col>
    </Row>
}
```

compiler error `Found a malformed 'Col' tag helper. Tag helpers must have a start and end tag or be self closing.`

**Comment by yoli799480165** [comment] 2020-07-10 10:31
Conflict with the html tag. not a bug of antd-blazor. you can fix like this:
    <Row Gutter="24">
        <AntDesign.Col Span="12">
            <h1>test1</h1>
        </AntDesign.Col>
        <AntDesign.Col Span="12">
            <h1>test2</h1>
        </AntDesign.Col>
    </Row>

**Comment by ElderJames** [comment] 2020-08-10 23:31
Use <Antdesign.Col> to workaround.

**Closed by ElderJames** 2020-08-10 23:31 UTC
Labels: wontfix
