### ISSUE TITLE
InputNumber not working with float/double values

### ISSUE THREAD

**Issue by momentum-tunis** [ant-design-blazor/ant-design-blazor#656] opened 2020-09-29 13:59 UTC
AntDesign Blazor version 0.3

InputNumber now throws an exception if I enter a decimal value. It as working well with stable build 0.2.

I use exactly the same code as the demo, if I enter 1.2 and then click outside the component it will throw an exception:

   
![image](https://user-images.githubusercontent.com/58601327/94568316-4145a300-0264-11eb-9b89-49dce65db82f.png)

![image](https://user-images.githubusercontent.com/58601327/94568465-69cd9d00-0264-11eb-847d-c373ef836b62.png)

**Comment by diegofrata** [comment] 2020-10-02 09:54
Can you please upgrade to the latest build and try again? I have been using this component in the latest builds and it is working with doubles.

**Comment by momentum-tunis** [comment] 2020-10-03 14:50
Hi, I tried with the latest version and still the same exception with parsing the value:

Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Input string was not in a correct format.
System.FormatException: Input string was not in a correct format.
  at System.Number.ThrowOverflowOrFormatException (System.Boolean overflow, System.String overflowResourceKey) <0x4ceeb48 + 0x0002a> in <filename unknown>:0 
  at System.Number.ParseDouble (System.ReadOnlySpan`1[T] value, System.Globalization.NumberStyles styles, System.Globalization.NumberFormatInfo info) <0x4cee928 + 0x0012a> in <filename unknown>:0 
  at System.Double.Parse (System.String s, System.Globalization.NumberStyles style, System.IFormatProvider provider) <0x4cee8a0 + 0x0003c> in <filename unknown>:0 
  at System.Convert.ToDouble (System.String value, System.IFormatProvider provider) <0x4cf6b20 + 0x00022> in <filename unknown>:0 
  at System.String.System.IConvertible.ToDouble (System.IFormatProvider provider) <0x4cf6a60 + 0x00006> in <filename unknown>:0 
  at System.Convert.ChangeType (System.Object value, System.Type conversionType, System.IFormatProvider provider) <0x352cfb0 + 0x0028e> in <filename unknown>:0 
  at System.Convert.ChangeType (System.Object value, System.Type conversionType) <0x352c350 + 0x0000e> in <filename unknown>:0 
  at AntDesign.InputNumber`1[TValue].ConvertNumber (System.String inputString) <0x4cd0790 + 0x00072> in <filename unknown>:0 
  at AntDesign.InputNumber`1[TValue].OnBlur () <0x4cbba50 + 0x0006c> in <filename unknown>:0 
  at Microsoft.AspNetCore.Components.EventCallbackWorkItem.InvokeAsync[T] (System.MulticastDelegate delegate, T arg) <0x377adb8 + 0x0006e> in <filename unknown>:0 
  at Microsoft.AspNetCore.Components.EventCallbackWorkItem.InvokeAsync (System.Object arg) <0x3777968 + 0x0000a> in <filename unknown>:0 
  at Microsoft.AspNetCore.Components.ComponentBase.Microsoft.AspNetCore.Components.IHandleEvent.HandleEventAsync (Microsoft.AspNetCore.Components.EventCallbackWorkItem callback, System.Object arg) <0x3777848 + 0x0000a> in <filename unknown>:0 
  at Microsoft.AspNetCore.Components.EventCallback.InvokeAsync (System.Object arg) <0x377b8e8 + 0x00040> in <filename unknown>:0 
  at Microsoft.AspNetCore.Components.RenderTree.Renderer.DispatchEventAsync (System.UInt64 eventHandlerId, Microsoft.AspNetCore.Components.RenderTree.EventFieldInfo fieldInfo, System.EventArgs eventArgs) <0x3d29af0 + 0x000a8> in <filename unknown>:0

**Comment by diegofrata** [comment] 2020-10-03 23:15
I will have a closer look at this and see what I can find.

**Comment by diegofrata** [comment] 2020-10-05 19:04
I think the issue is related to the culture set in the browser. The existing will take the user's culture and use it to parse the number in the input. Furthermore, the component doesn't really play well with decimal separators other than ".".

I'd suggest you try using the Parser and Formatter properties to implement a custom parsing/format that works irrespective of the culture you set!

**Comment by ElderJames** [comment] 2021-02-19 15:36
It may has been fixed via ##850.

**Closed** 2021-02-19 15:36 UTC
Labels: 🐛bug
