### ISSUE TITLE
Component 'Select' working incorrect inside 'Modal'

### ISSUE THREAD

**Issue by An2An96** [ant-design-blazor/ant-design-blazor#757] opened 2020-11-03 14:51 UTC
### Describe the bug
Dropdown is not displayed when 'Select' inside 'Modal', only a rectangular shadow appears.

### Further technical details
- AntDesign 0.3.0

**Comment by ElDiddi** [comment] 2020-11-03 17:41
Hi @An2An96 

i'm currently working on it. It will be fixed in my next PR.

**Comment by nelsonbatista** [comment] 2020-11-06 18:35
Hello,

In my case I found out that, the first page I enter, the dropdown works fine, all the times I open and close the Modal. If I then go to another page with a Modal with a Select, the Dropdown does not show.

I'm using AntDesign Blazor version 0.4.0-nightly-2011011445

Best regards,

**Comment by ElDiddi** [comment] 2020-11-06 20:29
The problem is that when you open the drop-down menu the width is not updated. If you need the solution directly you can insert `await SetDropdownStyleAsync();` in `Select.razor.cs - Line 348` then the width should be updated every time you open the drop down menu.

**Comment by nelsonbatista** [comment] 2020-11-09 09:07
Hello EIDiddi,

In my case, I'm using the nuget package in my projects. Do you know when this problem will be solved?

Best regards,

**Comment by ElDiddi** [comment] 2020-11-09 22:00
Hey @nelsonbatista,

I am currently rewriting the select module. Except for the group function, a few tests and the documentation I'm done. But this is a breaking change for the users, which James has to check and release first. I guess I should be finished within this week.

**Comment by ElderJames** [comment] 2020-11-10 00:58
Thank you @ElDiddi ,
I will recommend you as the collaborator after you fix the select.😉

**Comment by ElDiddi** [comment] 2020-11-15 13:27
Hello everyone,
I took a closer look at the problem. At first I thought that the problem occurs only with the Select module. But this is not the case, because the problem also occurs with the DropDown module. After a short examination of the Overlay module I found out that the problem is with the Modal module.
When you enter a website, the modal is created, as long as you are on the page it is reused. If you leave the page and visit the page again, a second modal is created. 
You can see the problem more clearly if you look at the HTML body and compare it. 

As a short term workaround you could set the property DestroyOnClose="true".

**Comment by ElderJames** [comment] 2020-11-15 15:53
cc @zxyao145

**Comment by nelsonbatista** [comment] 2020-11-16 10:17
Hello,

The property DestroyOnClose set to "true" worked for me, if I set it to all my app Modals.

**Comment by zxyao145** [comment] 2020-11-16 11:57
Hello,

In order to reuse the Modal dom, it will not be destroyed by default when modal is closed.

And, I can't reproduce this problem. Can anyone give me a demo?

**Closed** 2020-11-18 08:01 UTC
Labels: module: select
