### ISSUE TITLE
DatePicker with time input reverts value change when losing focus

### ISSUE THREAD

**Issue by bee-i-chris** [ant-design-blazor/ant-design-blazor#2767] opened 2022-10-05 11:28 UTC
### Describe the bug

When the current value in a DatePicker (with time) is changed in the input control and the user leaves the DatePicker, the changes are lost. 

### Steps to reproduce (please include code)

1. Go to https://antblazor.com/en-US/components/datepicker
2. In Example "Choose Time" select a date and time and click ok.
3. Click on DatePicker again. The popup window will open, but the cursor remains in the input field
4. Change the date or time with the keyboard, e.g. hit DEL and enter a new value.
5. Leave the control by hitting TAB or click outside the control.
6. Your change will be lost.

**Comment by Alexbits** [comment] 2022-10-05 17:57
@bee-i-chris The input in DatePicker with time should always be confirmed with the OK button or Enter key. Tab or clicking outside will revert the previous value, this is by design. From what I see, there is an issue with the Enter key to confirm the input. I will check this.

**Comment by Alexbits** [comment] 2022-10-05 18:32
Hey @ElderJames From what I see, the nuget and [antblazor.com](https://antblazor.com/en-US/components/datepicker) do not have the latest DatePicker fixes #2741 causing this and other issues. The master branch looks good, I can't replicate this issue, but I can replicate it on the [antblazor.com](https://antblazor.com/en-US/components/datepicker) and latest nuget. I'm not sure what's going on. 🤷‍♂️

**Comment by bee-i-chris** [comment] 2022-10-07 13:58
@Alexbits
Thanks for your quick answer. But I belive this is not was it should behave or something is wrong with the bits as you wrote.

Even the example on https://antblazor.com/en-US/components/datepicker behaves different. If you change the date by typing on the keyboard and leave the control by clicking outside with the mouse, the new value is accepted. This should be the default behavior. If the user makes an input it should be always accepted and only be cancelled, if the user hits ESC.

**Comment by Alexbits** [comment] 2022-10-07 15:57
@bee-i-chris @ElderJames The issue you are facing was fixed in one of my pull requests #2741. It looks like the example [](https://antblazor.com/en-US/components/datepicker) has the older version. The master branch looks good, you can clone the master branch and check how it works on your machine.

I'm trying to find out what's going on. We have to wait for @ElderJames to reply.

From what I understand, we're aiming for the same behavior as in the [ant.;design](https://ant.design/components/date-picker/)

**Comment by ElderJames** [comment] 2023-07-28 04:59
I think it's available now.

**Closed by ElderJames** 2023-07-28 04:59 UTC
