### ISSUE TITLE
select issue with multiple modals

### ISSUE THREAD

**Issue by lyjcooi** [ant-design-blazor/ant-design-blazor#814] opened 2020-11-21 02:43 UTC
### Describe the bug
当我一个页面有多个Model弹窗并且每个弹窗都有select选择框时，只有第一个打开的model能打开下拉列表，其它的就打不开了

When I have multiple modals on a page and each popup has a select box, only the first modal that opens will open the drop-down list, and the rest won't.

### Steps to reproduce (please include code)
```
<Modal Title=“modal1”>
<Select DefaultValue=@("0") Style="width:120px" @bind-Value="context.OptionReason">
                    <SelectOption Value="0">please select</SelectOption>
 </Select>
</Modal>
<Modal Title=“modal2”>
<Select DefaultValue=@("0") Style="width:120px" @bind-Value="context.OptionReason">
                    <SelectOption Value="0">please select</SelectOption>
 </Select>
</Modal>
```

不管你最先打开弹窗1 还是弹窗2  select 都能展开，但是后面打开的弹窗就都不能展开了 我试过设置 PopupContainerSelector属性，没有用

It doesn't matter if you open modal 1 first or modal 2 select, but the popover that opens later won't expand and I tried to set the PopupContainerSelector property, it didn't work

**Comment by ElderJames** [comment] 2020-11-21 03:13
感谢联系我们 @lyjcooi .
select的问题我们已经在修复，请跟踪这个PR #800 ，如果合并后仍有问题请再告诉我们。

**Comment by aelsheikh-emg** [comment] 2020-12-11 16:19
Hey @ElderJames I can confirm that this is still occurring in the latest pre-release build. My experience has been similar, when looking at the generated html I can see that the drop down elements are contained in a different modal.

**Comment by Magehernan** [comment] 2021-01-11 15:41
So, i update to 0.5.2 because i was having this problem in 0.4.1 but it continue failing... i found the problem but i don't not how to fix it... 
In my case, the problem is that the overlay is instantiating in the first modal that was opened so if it is the same it work fine, but if is it another it is hidden... i attach the tree of the html so you can see it...
If i open the same modal that it has the select it is ok..
![imagen](https://user-images.githubusercontent.com/28603584/104202372-a08d8480-5409-11eb-9377-44b036b1a203.png)
So if i open another modal and close it, then i open the modal with the select, this happend when i click on the select to see the options
![imagen](https://user-images.githubusercontent.com/28603584/104202850-31646000-540a-11eb-84e4-ebb0fdbf5d6a.png)
I will try to fix it looking for the parent modal of the element to instantiating it on the same modal.

**Comment by Magehernan** [comment] 2021-01-11 17:18
With DestroyOnLoad on all the modals it work fine... i really don't know how much performance you get for not destrying it so maybe is better that by default was true so you don't need to got to all modals and set to true.

Before it i try to fix it and i found that the problem is that the modal put a cascading parameter 
<CascadingValue Value=@(".ant-modal-wrap") Name="PopupContainerSelector">
so all modals have the same parameter so when something like the select that use this parameter, you have problems so it will find the first and it can be that is not your modal the first modal.... i try to add the Id on the class but the javascript function failed.

Hope this can be helpful

**Closed** 2021-01-21 11:07 UTC
