### ISSUE TITLE
SELECT Component Problem Inside MODAL When MaskClosable is False

### ISSUE THREAD

**Issue by hamiddd1980** [ant-design-blazor/ant-design-blazor#3521] opened 2023-11-20 12:17 UTC
### Describe the bug

When **SELECT** component (and **EnumSelect**) is inside a **MODAL** and the **MODAL** **MaskClosable** is set to **false** (by setting **MaskClosable** property), by clicking the **Arrow button** in **Select** component, **the drop-down section of SELECT component opens and then closes rapidly**. (**It doesn't remain in Open state**)
`(this happens if you exactly click the arrow button) `
### Steps to reproduce (please include code)

1-Add a Modal to page
2-Add a Select (or EnumSelect) to Modal
3-Set the Modal MaskClosable to false

```
<Modal Title="Select Inside Modal" Closable="false" MaskClosable="false"
       @bind-Visible="@isModalVisible">
    <Select TItem="Person"
            TItemValue="string"
            DataSource="@_list"
            @bind-Value="@_selectedValue1"
            DefaultValue="@("lucy")"
            ValueName="@nameof(Person.Value)"
            LabelName="@nameof(Person.Name)"
            DisabledName="@nameof(Person.IsDisabled)"
            Style="width:120px">
    </Select>
    <EnumSelect TEnum="@AvailableGrades" @bind-Value="@selectedGrade"></EnumSelect>
    
</Modal>

@code {
    public enum AvailableGrades
    {
        A,
        B,
        C,
        D,
        E,
        F,
        G,
        H,
        I
    }
    class Person
    {
        public string Value { get; set; }
        public string Name { get; set; }
        public bool IsDisabled { get; set; }
        public AvailableGrades Grade{ get; set; }
    }
    List<Person> _list;
    string _selectedValue1;
    private AvailableGrades selectedGrade;


   private bool isModalVisible;
   private Person newPerson = new();

    private void OpenModal()
    {
        isModalVisible = true;
    }
}

protected override void OnInitialized()
    {
        _list = new List<Person>
        {
            new Person {Value = "jack", Name = "Jack"},
            new Person {Value = "lucy", Name = "Lucy"},
            new Person {Value = "disabled", Name = "Disabled", IsDisabled = true},
            new Person {Value = "yaoming", Name = "YaoMing"},
            new Person {Value = "A", Name = "A1"},
            new Person {Value = "B", Name = "B1"},
            new Person {Value = "C", Name = "C1"},
            new Person {Value = "D", Name = "D1"},
            new Person {Value = "E", Name = "E1"},
            new Person {Value = "F", Name = "F1"},
            new Person {Value = "G", Name = "G1"},
            new Person {Value = "H", Name = "H1"},
            new Person {Value = "I", Name = "I1"},
            new Person {Value = "J", Name = "J1"},

        };
    }
```
### Further technical details
- AntDesign Nuget Package version : 0.16.2
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

**Comment by zxyao145** [comment] 2023-11-21 04:31
@hamiddd1980 Hi, it  seems to have been fixed in the latest version of SELECT, by #3520.

@ElderJames There is indeed a problem with 0.16.2, but the latest commit is working well, please confirm it.

**Comment by ElderJames** [comment] 2023-11-21 04:41
@zxyao145  This fix #3520 is about Tree not select.

**Comment by zxyao145** [comment] 2023-11-21 05:29
@ElderJames Are there any relevant code modifications? Please verify if the latest version works well for you,  and there is only the one commit between the latest version and 0.16.2.

**Comment by zxyao145** [comment] 2023-11-21 05:36
![2023-11-21_13-34-19](https://github.com/ant-design-blazor/ant-design-blazor/assets/24973084/f14f23dc-b922-4896-8322-ab97bb4f99fc)

**Comment by hamiddd1980** [comment] 2023-11-21 16:34
Thank you for your reply.
I'm using **AntDesign** Version **0.16.2**. In order to view the problem, the **Modal MaskClosable** should be false and you should  exactly click the **Arrow button** of component.(please view the below video):


![Select-In Modal](https://github.com/ant-design-blazor/ant-design-blazor/assets/57061231/0c7a77d6-41b4-43a8-900e-d60b3cc17ac7)

**Comment by zxyao145** [comment] 2023-11-22 12:12
@hamiddd1980 
Got, I have reproduced it: I must and can only click on the arrow.

**Comment by zxyao145** [comment] 2023-11-23 05:48
@hamiddd1980 Hi, when exploring this issue, I found it to be a very interesting thing.
 
**Blazor and JS have different mechanisms for event processing**, or are limited to JS's single threaded running environment. Blazor handles events asynchronously, while JS can only process the next event after one event has been processed (Event Loop model).


For the code of the blazor below:

```razor
<div id="parent"
     @onmouseup="OnParentMouseUp">
    <div id="child"
         @onmouseup="OnChildMouseUp">
        child
    </div>
</div>


@code {

    private void OnParentMouseUp()
    {
        Console.WriteLine("3 Parent mouseup");
    }

    private async Task OnChildMouseUp()
    {
        Console.WriteLine("1 Child mouseup");

        await Task.Delay(10000);

        Console.WriteLine("2 Child mouseup end");
    }
}
```

This will output "3 Parent mouseup" first and then "2 Child mouseup end".

![image](https://github.com/ant-design-blazor/ant-design-blazor/assets/24973084/2cfbbe8d-571d-4ccd-93b1-938df257364b)


But if we use JS to implement this code:
```html
<div id="parent">
    <div id="child">
      child
    </div>
  </div>
  <script>
    document.getElementById("parent").addEventListener("mouseup", () => {
      console.log("3 parent mouseup");
    });

    document.getElementById("child").addEventListener("mouseup", () => {
      console.log("1 child mouseup");
      // Simulate a time-consuming operation
      for (let i = 0; i < 10_0000; i++) {
        var text = i + "j: ";
        for (let j = 0; j < 10_000; j++) {
          text += " " + j;
        }
      }
      console.log("2 child mouseup end");
    });

    const sleep = time => {
      console.log("sleep");
        return new Promise(resolve => setTimeout(resolve, time)
        )
      } 
  </script>
```

This is the normal event bubbling of JS. Unless we use setTimeout (NOT Promise) to wrap the for-loop code, we will not be able to observe the output is in the order of 1, 3, 2

![image](https://github.com/ant-design-blazor/ant-design-blazor/assets/24973084/a3d7e9f2-f066-4713-9a06-8a9c6f563393)

According to the event model of JS, the triggering order of mouseup and click events should be `child-mouseup` -> `parent-mouseup` -> `child-click` -> `parent-click`. 

Due to the mixed use of Blazor and Js event handling mechanisms, `parent-mouseup` has not yet been executed, while `child-click` has already been executed.

Therefore, in the MouseUp of OverlayTrigger, it is necessary to ensure that the click event is executed completely.

Finally, I will fix this issue as soon as possible.

**Comment by ElderJames** [comment] 2023-11-23 06:00
@zxyao145 I think this issue is a bit same to https://github.com/ant-design-blazor/ant-design-blazor/issues/3353

**Comment by zxyao145** [comment] 2023-11-23 06:07
> @zxyao145 I think this issue is a bit same to #3353

Yes, the events of OverlayTrigger are not executing in the expected order

**Comment by ElderJames** [comment] 2023-11-25 08:18
Maybe another issue https://github.com/ant-design-blazor/ant-design-blazor/issues/3495 is also related with this

**Closed** 2024-08-04 15:13 UTC
