### ISSUE TITLE
Is Ant design blazor support RTL or NOT?

### ISSUE THREAD

**Issue by khaledalmolaa** [ant-design-blazor/ant-design-blazor#824] opened 2020-11-23 20:04 UTC

**Comment by ElderJames** [comment] 2020-11-24 04:25
Thank you for contacting us @khaledalmolaa .

We haven't supported RTL yet. But the styles are supported because they are sync from ant-design.
So if you can help us implement this feature, we'd really appreciate it.
If you have any ideas, just feel free to create a PR.

**Comment by Epictek** [comment] 2020-11-24 10:17
Duplicate of #275

**Closed by Epictek** 2020-11-24 10:17 UTC
Labels: duplicate, enhancement, help wanted
