### ISSUE TITLE
RangePicker clicks on a different area to close the date box for a bug that triggers the onChange event of the old value

### ISSUE THREAD

**Issue by GlodenBoy** [ant-design-blazor/ant-design-blazor#2713] opened 2022-09-15 02:51 UTC
RangePicker 点击其他区域关闭日期框会触发返回一个旧值的OnChange事件的BUG，如下图所示：

> RangePicker Clicking on another area to close the date box triggers a BUG that returns an old Value OnChange event, as shown in the following figure:

![image](https://user-images.githubusercontent.com/2329528/190302086-3934543c-e602-4cc0-b61d-f7d29e8a1551.png)

只有按下拉框里的确定按钮关闭才不会触发旧的Onchange事件

> Only pressing the OK button in the drop-down box to close does not trigger the old Onchange event

所以点击其他区域关闭日期框是不是不应该触发一个Onchange?

> So clicking on other areas to close the date box shouldn't trigger an Onchange?

code：
`<RangePicker OnChange="OnDatePickChange"  AllowClear="@false" Value="@(new DateTime?[] {)" TValue="DateTime?[]" ShowTime='@("HH:mm")' Format="MM-dd HH:mm"/>`

**Comment by ColinZeb** [comment] 2022-09-15 16:15
RangePicker 无法选择月份年份和这个有关吗，无论是wasm 还是 server，甚至演示文档都有这问题
Is this related to RangePicker's inability to select month and year, both in wasm and server, and even in presentations?

**Comment by Alexbits** [comment] 2022-09-15 18:50
@GlodenBoy The OnChange event is triggered whenever the date is selected on the panel, and the OK button does not trigger this event. When you do not confirm the selected date with the OK button and click on the empty space to close the dropdown, the event is triggered because the value is changed from the last selected to the previously selected one.

I was thinking about this earlier and maybe the OK button should trigger the OnChange event when both start and end values are confirmed, in the case of RangePicker. I'm not sure how this works in the original ant.design. What do you think @ElderJames?

**Comment by GlodenBoy** [comment] 2022-09-16 02:37
@Alexbits

**Comment by Alexbits** [comment] 2022-09-16 06:19
> @Alexbits
> 
> I think clicking on a date triggers an Onchange event is right, I just don't understand that clicking on an empty area to close the drop-down date box after I've selected 2 dates will trigger an Onchange event with the wrong value, which shouldn't need to be triggered because the values have already been changed.

@GlodenBoy
The OnChange should not be triggered by the closed dropdown. This will be fixed.

> Should the behavior of clicking on an empty area to close the drop-down box be consistent with the behavior of the OK button?

No, it should not have the same behavior as the OK button. It reverts the value to the previous one or clears it if not confirmed with the OK button.

**Comment by GlodenBoy** [comment] 2022-09-16 14:15
> > @Alexbits
> > 
> > I think clicking on a date triggers an Onchange event is right, I just don't understand that clicking on an empty area to close the drop-down date box after I've selected 2 dates will trigger an Onchange event with the wrong value, which shouldn't need to be triggered because the values have already been changed.
> 
> @GlodenBoy
> The OnChange should not be triggered by the closed dropdown. This will be fixed.
> 
> > Should the behavior of clicking on an empty area to close the drop-down box be consistent with the behavior of the OK button?
> 
> No, it should not have the same behavior as the OK button. It reverts the value to the previous one or clears it if not confirmed with the OK button.
> 
> 

After that, is it necessary to go through the OK button to trigger the onchange? Because the user may not click OK but directly click on another date or close it, now it is controversial whether closing the window does not need to restore the value when it is not pressed OK?

**Comment by Alexbits** [comment] 2022-09-16 15:41
> After that, is it necessary to go through the OK button to trigger the onchange? Because the user may not click OK but directly click on another date or close it, now it is controversial whether closing the window does not need to restore the value when it is not pressed OK?

@GlodenBoy 
When the OK button is present, it's necessary to confirm with the OK button. Otherwise, there is not much sense in the OK button. The OK button is present only when the time selection panel is visible. This is how it's done in the ant.design.

**Comment by GlodenBoy** [comment] 2022-09-17 03:02
> 

But now there is no way for me to get the latest value, because the value returned by the onchange event is messy, how do I get the latest value instead of letting it be restored?

Maybe it's possible to come up with an API to set it up?

@Alexbits

**Comment by Alexbits** [comment] 2022-09-17 06:51
> > 
> 
> But now there is no way for me to get the latest value, because the value returned by the onchange event is messy, how do I get the latest value instead of letting it be restored?
> 
> Maybe it's possible to come up with an API to set it up?
> 
> @Alexbits

Please read the above and wait a bit while the OnChange behavior will be fixed.

**Comment by ElderJames** [comment] 2022-09-17 07:02
Thank you @Alexbits

**Comment by GlodenBoy** [comment] 2022-09-22 08:33
@Alexbits  

Hello friend, please ask how is your side of the progress, my project this problem is not very good to bypass, because I will send a request to change the data every time I change, because it will be restored, so there will be an extra restore request and log, which is not very friendly.

**Comment by Alexbits** [comment] 2022-09-22 08:42
@GlodenBoy I plan to submit a pull request this week with improvements

**Comment by GlodenBoy** [comment] 2022-09-22 08:44
> @GlodenBoy I plan to submit a pull request this week with improvements

Thank you so much!

**Closed** 2022-09-27 06:41 UTC

**Comment by GlodenBoy** [comment] 2022-10-11 02:53
#2782 0.12.5 Bug  @Alexbits
