### ISSUE TITLE
If form non-empty validation should be disabled when input has been disabled

### ISSUE THREAD

**Issue by bingbingtalk** [ant-design-blazor/ant-design-blazor#516] opened 2020-08-18 13:40 UTC
表单中其中一下输入框在禁用状态时能否在自动验证时不进行非空等验证

If form non-empty validation should be disabled when input has been disabled.

**Comment by anddrzejb** [comment] 2021-01-24 13:21
@bingbingtalk I do not think this can be done directly by the `AntDesign`. The problem is that when validation is executed (it is done in `Required` validation attribute) the method does not know anything about controls bound to the properties. And I do not think they should (imagine a scenario when a single property is bound to several different DOM elements). However this can be done with a custom validation attribute and once PR #1035 is merged. Example:
```razor
@using System.ComponentModel.DataAnnotations;
<h3>AntDesign.Form</h3>
<Form Model="@Model" @ref="form">
    <Validator>
        <DataAnnotationsValidator />
    </Validator>
    <ChildContent>
        <FormItem Label="User Name">
            <Input @bind-Value="@context.UserName" Disabled="@Model.Disabled" />
        </FormItem>
        <FormItem Label="Password">
            <InputPassword @bind-Value="@context.Password" />
        </FormItem>
        <button type="submit">Save</button>
    </ChildContent>
</Form>
<br />
<Checkbox Checked="@Model.Disabled" CheckedChange="@ToggleChecked">Disable username</Checkbox>

@code {
    AntDesign.Form<LoginModel> form;

    LoginModel Model = new LoginModel();

    protected override async Task OnInitializedAsync()
    {
        this.Model = new LoginModel
        {
            UserName = "Tom",
            Password = "123456",
        };
        await base.OnInitializedAsync();
    }

    public class LoginModel
    {
        [RequiredUnlessDisabled]
        public string UserName { get; set; }
        [Required]
        public string Password { get; set; }
        //adding this property will actually allow to check the state of input box during validation
        public bool Disabled { get; set; }
    }

    private void ToggleChecked(bool value)
    {
        Model.Disabled = value;
        if (Model.Disabled)
            Model.UserName = null;
        //validation needs to be reset once the form input box disability is changed
        //this is part of PR #1035 that will need to be merged for this solution to work
        form.ValidationReset();
    }

    public class RequiredUnlessDisabled : RequiredAttribute
    {
        protected override ValidationResult IsValid(object value, ValidationContext validationContext)
        {
            var model = (LoginModel)validationContext.ObjectInstance;
            if (model.Disabled)
                return ValidationResult.Success;

            if (value == null)
            {
                return new ValidationResult("Value is required.", new[] { validationContext.MemberName });
            }

            return ValidationResult.Success;
        }
    }
}
```

The only thing I did not solve is the asterix indicating that it is a required when in fact it is disabled and not required. But maybe you can do this here?

**Comment by anddrzejb** [comment] 2021-02-22 09:58
@ElderJames maybe we could add this sample somewhere in the docs? I do not think we can do anything here, aside from what I proposed. Maybe we could request @Hona to include this idea in his #1131?

**Comment by anddrzejb** [comment] 2021-03-05 06:54
Closing this issue as there is nothing we can do here.

**Closed by anddrzejb** 2021-03-05 06:54 UTC
Labels: enhancement
