### ISSUE TITLE
Menu drop-down lists does not close

### ISSUE THREAD

**Issue by true-perfect-code** [ant-design-blazor/ant-design-blazor#1075] opened 2021-02-03 15:06 UTC
### Describe the bug

![image](https://user-images.githubusercontent.com/45635963/106764777-67c38280-6638-11eb-87e8-e3eb52ebec18.png)

The Menu component is really good, but there is one small thing that leaves a bad impression on the user. It is about hiding the options. This problem with hiding seems to exist in general, because you have it also in ToolTip (you can see it in the picture).

Specifically, in the given image, we dragged the mouse from left to right in the horizontal menu bar normally (not too fast, not too slow) and the drop-down lists gradually opened but did not close again.

We have seen that two parameters are provided in the API for the menu :
- SubMenuCloseDelay
- SubMenuOpenDelay

We hope that with the next version it will be possible to solve the problem with these two parameters.

Thanks

Translated with www.DeepL.com/Translator (free version)

### Steps to reproduce (please include code)
we dragged the mouse from left to right in the horizontal menu bar normally (not too fast, not too slow) and the drop-down lists gradually opened but did not close again.

### Further technical details
- AntDesign Nuget Package version 0.6
- Community 2019

**Comment by true-perfect-code** [comment] 2021-02-04 09:25
Workaround:
If I set AutoCloseDropdown="true", it seems to be much better. At least I could not reproduce the effect anymore.

With ToolTips, unfortunately, it still exists (it's clear, because AutoCloseDropdown="true" refers only to Menu).

Tested in 0.7

**Comment by true-perfect-code** [comment] 2021-03-05 18:03
Is there anything new regarding the menus? Unfortunately, the problem still exists. I was wrong in the last post, it seemed like it was getting better, but it wasn't.

Thanks

**Comment by mutouzdl** [comment] 2021-04-02 07:09
@true-perfect-code 
Sorry for the late reply.
Could you provide an example or code? I couldn't reproduce the issue by the steps you provide.

----------------------------
不好意思，回复地有点晚。
可以提供一个例子或者代码吗？我按照你提供的步骤没法重现这个问题。

**Comment by true-perfect-code** [comment] 2021-04-02 07:52
Hi mutouzdl 

Unfortunately, I got away from the menu component and replaced it with a self-built HTML/CSS menu.

However, it should not be difficult to reproduce the problem. Take the menu component and create it in horizontal view. But make a few more menu items than in your example and you will see that the opened menu items hang up. I tested this with version 0.7 before switching to HTML/CSS and the error was there. Since we don't have any more time, I just replaced the component.

However, Ant-Blazor is an excellent UI component that we use exclusively! Respect for the great development!

Greetings

**Comment by johnnyzheng99** [comment] 2021-07-28 09:26
> @true-perfect-code
> Sorry for the late reply.
> Could you provide an example or code? I couldn't reproduce the issue by the steps you provide.
> 
> 不好意思，回复地有点晚。
> 可以提供一个例子或者代码吗？我按照你提供的步骤没法重现这个问题。

Please kindly go to this page and check out this vertical menu. 
https://antblazor.com/en-US/components/menu
![image](https://user-images.githubusercontent.com/1889386/127297365-44ec029c-0293-40f5-bda4-1f3f7e62b21b.png)

To reproduce it, Simply move mouse over the menu items. You will be able to see what happens. The new menu item opens up but the old opened menu items just do not close first. There are multiple menu items showing up simultaneously for a while then the old ones close. Note that if you open it in horizontal, the main menu on the top has the same issue. 

It feels bad to see this in production environment. The bug has existed for long and it is odd that it has still not been fixed in the latest release. We had to choose to use a third party top menu component too but it would be great if this can be fixed.

**Comment by johnnyzheng99** [comment] 2021-07-28 09:34
https://antblazor.com/en-US/components/popover

If you go to this page, do try to move your mouse over the two popover items relatively faster, you will be able to see this bug as well. If you have more items, you will be able to replicate this problem even more easier. 

I guest the popever and the menu items share a share js animation function or css animation which delays the closure of the opened items. Tracing into the js you can see the function has some odd behaviour treating the statuses of the items.

The correct logic will be simply closing the opened menu first then show the new item at all times.

![image](https://user-images.githubusercontent.com/1889386/127299009-280e94b6-2daa-4cc4-8704-f3e2ee6c1b11.png)

**Closed** 2021-09-10 11:06 UTC
