### ISSUE TITLE
Form IsModified not changed after data input

### ISSUE THREAD

**Issue by wuxj74** [ant-design-blazor/ant-design-blazor#1333] opened 2021-04-10 08:51 UTC
### Describe the bug

Hi,

Try the sample in this url:
https://antblazor.com/zh-CN/components/form#components-form-demo-is-modified

input Username or Password, submit button is still disabled.

### Further technical details
- AntDesign Nuget Package version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

**Comment by anddrzejb** [comment] 2021-04-13 19:16
This is basically a duplicate of #1139. A PR fixing the docs has been created.

**Closed by anddrzejb** 2021-04-13 19:16 UTC
