### ISSUE TITLE
Select Mode=multiple dont bind selected values from model in Form

### ISSUE THREAD

**Issue by valentasm1** [ant-design-blazor/ant-design-blazor#1428] opened 2021-04-28 06:27 UTC
### Describe the bug

Select with multiple mode dont assign values when it is used in form element. Works well when used without form

### Further technical details
- AntDesign Nuget Package version 0.8.0
- Using blazor Wasm

Code to reproduce
```
@page "/admin/users-test"
@attribute [Authorize]

@using System.ComponentModel
@using AntDesign.TableModels


<Form Model="@model"
      OnFinish="OnFinish"
      OnFinishFailed="OnFinishFailed"
      LabelColSpan="8"
      WrapperColSpan="12">
    <FormItem Label="Items">
        <Select Mode="multiple"
                Placeholder="Please select"
                DataSource="@_options"
                @bind-Values="@context.SelectedValues"
                LabelName="@nameof(AdminRole.Name)"
                ValueName="@nameof(AdminRole.Id)"
                TItemValue="string"
                TItem="AdminRole">
        </Select>
    </FormItem>
    <FormItem WrapperColOffset="8" WrapperColSpan="16">
        <Button Type="@ButtonType.Primary" HtmlType="submit">
            Save
        </Button>
    </FormItem>
</Form>
@code
{
    public class AdminRole
    {
        public AdminRole(string name, string id)
        {
            Name = name;
            Id = id;
        }

        public string Name { get; set; }

        public string Id { get; set; }
    }

    public class Admin
    {
        public IEnumerable<string> SelectedValues { get; set; } = new List<string>();
    }

    private Admin model = new Admin();

    List<AdminRole> _options;
    protected override async Task OnInitializedAsync()
    {
        _options = new List<AdminRole>();
        _options.Add(new AdminRole("admin", "admin"));
        _options.Add(new AdminRole("kid", "kid"));
        _options.Add(new AdminRole("teacher", "teacher"));

        model = new Admin()
        {
            SelectedValues = new List<string>() { "admin" }
        };

        await Task.Delay(1000);
    }

    private async Task OnFinish(EditContext editContext)
    {
    }

    private void OnFinishFailed(EditContext editContext)
    {
    }
}
```

**Comment by anddrzejb** [comment] 2021-04-28 06:41
Duplicate of #1120

**Comment by anddrzejb** [comment] 2021-04-28 07:30
As a poor's man workaround I did something like this:
```razor
    <Row class="ant-form-item ant-row" style="row-gap: 0px;">
        <AntDesign.Col class="ant-form-item-label">
            <label>A label</label>
        </AntDesign.Col>
        <AntDesign.Col class="ant-form-item-control ant-col ant-col-20">
            <AntDesign.Select 
                                @bind-Values="@_selectedValues"
                                Mode="multiple"
                                DataSource="@dataSource"
                                TItem="Item"
                                TItemValue="int"
OnSelectedItemsChanged="@OnRecipientsChange"
                                AllowClear>
            </AntDesign.Select>
            @*@_formValidationMessages*@
        </AntDesign.Col>
    </Row>
```
You have to handle your validation messages manually I am afraid...

**Closed** 2021-05-06 05:42 UTC
Labels: duplicate
