### ISSUE TITLE
Message Info report: Key values must be unique

### ISSUE THREAD

**Issue by Forfires** [ant-design-blazor/ant-design-blazor#3651] opened 2024-01-26 08:59 UTC
I use it in Blazor Hybird, and when the program pops up messages several times, the program reports an error: 

> InvalidOperationException: More than one sibling of component 'AntDesign.MessageItem' has the same key value, 'AntDesign.MessageConfig'. Key values must be unique.

I called it as follows

`
 _ = _message.Info(notification.Message);
`

**Comment by zxyao145** [comment] 2024-01-29 01:34
@Forfires Hi, What is the type of notification.Message? Is it `MessageConfig`? If so, please ensure that different references are passed, such as using `_ = _message.Info(new MessageConfig(){ .... });`

**Comment by Forfires** [comment] 2024-02-01 06:42
I've tried calling it this way,but the problem persists
`   _ = _message.Info(new MessageConfig()
       {
           Content = "保存成功",
           Key = Guid.NewGuid().ToString()
       });`

**Comment by Forfires** [comment] 2024-02-01 06:46
It should be added that I triggered this method about 80 times in 10 seconds

**Comment by zxyao145** [comment] 2024-02-04 02:03
@Forfires Hi, it requires more context information, which I did not reproduce locally, or you can provide a demo. 

This is my demo, I click the button once per second, it works well.

```razor

@inject MessageService _messageService

<Button Type="primary" OnClick="@ShowMsg">
    ShowMsg
</Button>

@code {

    private void ShowMsg()
    {
        for (int i = 0; i < 10; i++)
        {
            _messageService.Info(
                new MessageConfig()
                {
                    Content = "保存成功",
                    Key = Guid.NewGuid().ToString()
                });
        }

        _messageService.Info(
            new MessageConfig()
            {
                Content = "END",
                Key = Guid.NewGuid().ToString(),
                Duration = 5
            });
    }
}
```

**Comment by ElderJames** [comment] 2024-02-04 02:46
Is it possible that multiple AntContainters are set up?

**Comment by Forfires** [comment] 2024-02-20 16:19
> @Forfires Hi, it requires more context information, which I did not reproduce locally, or you can provide a demo.
> 
> This is my demo, I click the button once per second, it works well.
> 
> ```
> @inject MessageService _messageService
> 
> <Button Type="primary" OnClick="@ShowMsg">
>     ShowMsg
> </Button>
> 
> @code {
> 
>     private void ShowMsg()
>     {
>         for (int i = 0; i < 10; i++)
>         {
>             _messageService.Info(
>                 new MessageConfig()
>                 {
>                     Content = "保存成功",
>                     Key = Guid.NewGuid().ToString()
>                 });
>         }
> 
>         _messageService.Info(
>             new MessageConfig()
>             {
>                 Content = "END",
>                 Key = Guid.NewGuid().ToString(),
>                 Duration = 5
>             });
>     }
> }
> ```
I tried the above code, the error still exists, the same code runs fine in the browser, but I am using winform and blazor webview. Could it have anything to do with this? As for AntContainter, I only add it once in App.razor.
![微信图片_20240221001751](https://github.com/ant-design-blazor/ant-design-blazor/assets/4706175/27a4ac56-5bc0-46c3-8eb2-85b847a2fe73)
![微信图片_20240221001855](https://github.com/ant-design-blazor/ant-design-blazor/assets/4706175/13332003-faa6-48fe-ac9d-36d5ed1546de)

**Comment by zxyao145** [comment] 2024-02-21 01:28
@Forfires Sorry, I haven't used winform+ blazor webview before. I will try again later

**Comment by zxyao145** [comment] 2024-02-23 07:36
@Forfires Hi, I have successfully reproduced this issue on webview. 

`Message` will use a `List` internally to save the MessageConfigs, and If both `Add` and `Remove` operations are performed on this `List` at the same time (the scheduled deletion operation uses Task, therefore, these two operations may be on different threads), it is this is non thread safe in WebView, but thread safe in Browser. Because the CLR of the two is different, the `TaskScheduler` is also different, in a browser environment, there is actually only one thread.

This issue will be fixed as soon as possible.

**Closed** 2024-02-28 15:29 UTC
