### ISSUE TITLE
Carriage jumps around after filtering table

### ISSUE THREAD

**Issue by henrikwidlund** [ant-design-blazor/ant-design-blazor#3650] opened 2024-01-25 16:55 UTC
### Describe the bug

The carriage resets to end of line and the whole interface gets less responsive after the first use of a filter on a table cell using the default implementation of `Filterable`.

https://github.com/ant-design-blazor/ant-design-blazor/assets/4659350/d4fd93b9-85c1-4254-9480-8be74279d09f

This happens on both the sample site as well as locally using SSR. When using SSR there's a never-ending flood of messages from the SignalR hub used by Blazor. I suspect something is triggering an update in an infinite loop.

### Steps to reproduce (please include code)
1. Browse to https://antblazor.com/en-US/components/table#components-table-demo-generate-columns (any of the examples with a similar filter produces the same issue)
2. Enter something in the Address filter
3. Click OK
4. Open the same filter again and try to move the carriage position
5. Carriage keeps moving to the end of the line

### Further technical details
- Server Side Blazor
- AntDesign: 0.17.3.1
- AntDesign.ProLayout: 0.17.3
- Rider 2023.3.3
```
dotnet --info
.NET SDK:
 Version:           8.0.101
 Commit:            6eceda187b
 Workload version:  8.0.100-manifests.69afb982

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  14.2
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /usr/local/share/dotnet/sdk/8.0.101/

.NET workloads installed:
 Workload version: 8.0.100-manifests.69afb982
There are no installed workloads to display.

Host:
  Version:      8.0.1
  Architecture: arm64
  Commit:       bf5e279d92

.NET SDKs installed:
  8.0.101 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found
```

**Comment by ElderJames** [comment] 2024-01-28 14:26
Thanks for contacting us @henrikwidlund . This seems to be related to the autofocus of the filter's input. @m-khrapunov please take a look on this issue.

**Comment by sdt-shigeo-hamada** [comment] 2024-02-08 01:27
The cause may be the same as reported, but when a filter item is added, the focus moves to the first input item, so the input to the added item cannot be performed.

If the first input component is deleted and then added, the cursor is not forced to move, but it reappears when reset.

Thank you in advance for your help.

**Comment by dzima1** [comment] 2024-02-13 15:58
Hi, i think this issue might be similar to this one: 

I'm observing jumping between filter inputs when there are more than one:
![chrome-capture-2024-2-13](https://github.com/ant-design-blazor/ant-design-blazor/assets/2502169/e81ca7b7-59e5-432a-8c72-a94ddc55f3fd)

**Comment by m-khrapunov** [comment] 2024-02-14 07:49
The fix has been prepared. It should works as expected.


https://github.com/ant-design-blazor/ant-design-blazor/assets/93575828/51c8e0a5-6bcc-4aef-b329-eaf400316fa8

**Closed** 2024-02-20 14:46 UTC
