### ISSUE TITLE
Is there any way we configure our data table in a separate class?

### ISSUE THREAD

**Issue by arashabbac** [ant-design-blazor/ant-design-blazor#1455] opened 2021-05-03 06:19 UTC
Hi , Thanks for your amazing and helpful tool
 
Is there any way we configure our data table features in a separate class so we use them everywhere in our project and when we want to do any changes we just change that class?

I don't mean to create a base component , I just want to create a class  to configure data table and add an auto increment column for every table I use in my project

Is there any way to do that?
Unfortunately I can not find any documentation for Table

please answer me ASAP
Thanks in advance

**Comment by anranruye** [comment] 2021-05-04 01:21
Some personal suggestions:

You can use a `Dictionary<string, object>` to store and resue attributes configuration for any kind of components. To apply the configuration, use `@attributes` attribute for your components.

To resue column configuration, you need to implement a mechanism to convert your config class instances to `RenderFragment<TItem>` which can be assigned to a table's `ChildContent` attribute.

> add an auto increment column for every table I use in my project
Do you mean you want to add a row number column to your table? It seems that row number column is not supported yet.

**Comment by arasheyn** [comment] 2021-05-04 08:45
thank you for answering me

Do you have any best practice for that? if you do me a favor and show me
how to implement , I would really appreciate it

And you're telling me that I can't add a column row number for my table ?
Isn't there any way to do it manually?

**Comment by anranruye** [comment] 2021-05-04 13:21
To add a rownumber column, if you don't want to modify the source code, you can use `OnRow` attribute to set a html attribute to the generated `<tr>` element, then you can use css only to achieve this goal. For more information about 'OnRow' attribute, see https://antblazor.com/en-US/components/table#components-table-demo-on-row-and-on-cell.

Here's an example:
```
<Table ... OnRow="OnRow">
...
</Table>

@code{
    Dictionary<string, object> OnRow(RowData<WeatherForecast> row) => new Dictionary<string, object>()
    {
        { "rownumber", row.RowIndex }
    };
}

<style>
    .ant-table-tbody tr::before {
        content: attr(rownumber);
    }

    .ant-table-thead tr::before {
        content: '';
    }
</style>
```

The effect looks like:
![image](https://user-images.githubusercontent.com/54608128/117008826-b529bb80-ad1d-11eb-98eb-9f1ca03f42e3.png)

Not good, but it does work.

For a better appearance, it's better to modify the source code of ant-desgin blazor. This won't be difficult becasuse the table cells do receive the `RowData` object form a cascade paramter(but there is no interface exposed to let user use it). However, you must download the source code and build the project on your local machine.

**Comment by arasheyn** [comment] 2021-05-04 15:41
Thank you very much for your help
Do you have any documentation for this Table component?
I searched all over the net but I couldn't find anything at all !

How can I get my hands on the source code? do you mean I download it from
github and then how can I add it to my project? because I use Nuget
packages for adding new libraries

**Comment by anranruye** [comment] 2021-05-05 00:02
Wait, it's strange that you can not find any documentation. How do you get started with no documentation? Are you using ant-design pro components? Which nugget packages are you using?

**Comment by arasheyn** [comment] 2021-05-05 05:44
I'm using this AntDesign:

https://antblazor.com/en-US/components/overview

And this Nuget package:
<PackageReference Include="AntDesign" Version="0.8.0" />

Some of its components have API section that explain what properties
include in that component , but Table component didn't have this part !
And everywhere I found any documentation , they just explain how to
install  AntDesign in our projects , they didn't explain anything about its
components

**Comment by anranruye** [comment] 2021-05-05 06:44
Yes, there is no API section for `Table`. But this doesn't matter.

Loacl build method is in the readme file:
![image](https://user-images.githubusercontent.com/54608128/117104902-878d5280-adaf-11eb-9bd6-becdd9e3c55a.png)

For short, you need install Node.js for building style files and interoperable TypeScript files. 
Then download the project source files by clone or download a zip package.
![image](https://user-images.githubusercontent.com/54608128/117105073-dfc45480-adaf-11eb-9f9f-7d4c82e86853.png)
Then copy the AntDesign project to your own solution folder 
![image](https://user-images.githubusercontent.com/54608128/117105165-0da99900-adb0-11eb-82dd-fc79deffec01.png)
Then add a project reference to the AntDesign project
![image](https://user-images.githubusercontent.com/54608128/117105311-52353480-adb0-11eb-9737-a2a0d997c2b8.png)

**Comment by arasheyn** [comment] 2021-05-05 06:54
Thank you for your help , I don't understand why you didn't publish the Docs
You mean that I have to download the whole package and reference it to my
project instead of using Nuget packages so I can access documents or
you mean I do this for changing the source code that you mentioned earlier?

Is this the only way for accessing the documentation?

**Comment by anranruye** [comment] 2021-05-05 07:27
> or you mean I do this for changing the source code that you mentioned earlier?

Yes

> Is this the only way for accessing the documentation?

I don't understand what 'documentation' means for you? For me, https://antblazor.com/en-US/components/overview this is the documentation. What are you looking for?

**Comment by arasheyn** [comment] 2021-05-05 18:23
Sorry if I get you angry😑
For example I didn't know there was a "OnRow" property since you introduced
it to me
My mean about documentation is that , where I can access and know all the
properties that component has , so I could use them and change them for my
business
As I mentioned earlier , some of components has API section at the bottom
of the page and you introduced the properties that we could use for that
component,
but as you confirmed , there isn't for Table component

I hope I was able to get what I meant

**Comment by anranruye** [comment] 2021-05-05 23:30
Yes, the document is not perfect. It's behind the code development. Some new features or possible usage for exsisting features are not introduced in it. Even though you get all properties(for example by F12 in vs), it's hard to use them efficiently without a demo. Another example is that some data types shown in the api list is not changed to .NET types. 

Feel free to help improve the documentation or give suggestions

**Comment by arasheyn** [comment] 2021-05-07 12:36
I want to do some configuration , If you could help me I would appreciate
it.

I want to create a class outside of the component for configuring the Table
component such as style and add an auto increment column, and in every page
I use this component I add an instance of that Table into this configure
class in OnInitialize method.


*Index.razor*

























*              <Table @ref="table"
 ***@***.***Result"                       Total="data.TotalCount"
                   PageSize="data.PageSize"
 Loading="@_table.Loading"
 OnPageIndexChange="pageIndexChanged">                    <Column
Class="@_table.ColumnCssClass" Title="@Resources.DataDictionary.IsActive"
@***@***.***IsActive">                        <Checkbox
***@***.***IsActive" Disabled="true" />
</Column>                    <Column Class="@_table.ColumnCssClass"
Title="@Resources.Models.Users.FullName" @***@***.***FullName"
/>                    <Column Class="@_table.ColumnCssClass"
Title="@Resources.Models.Users.EmailAddress"
@***@***.***EmailAddress" />                    <Column
Class="@_table.ColumnCssClass" Title="@Resources.Models.Users.UserType"
***@***.***UserTypeValue" />                    <Column
Class="@_table.ColumnCssClass" Title="@Resources.DataDictionary.Action"
@***@***.***Id">                        <Tooltip
Title="@(Resources.Actions.Edit)">                            <a
***@***.***Id"><i class="typcn typcn-edit"></i></a>
                </Tooltip>                        <Tooltip
Title="@(selectGroup)">                            <a
***@***.***Id"><i class="typcn
typcn-group-outline"></i></a>                        </Tooltip>
        </Column>                ***@***.***{*






*    private ViewPagingDataResult<ViewModels.User.UserViewModel> data {
get; set; }    AntDesign.Table<ViewModels.User.UserViewModel> table;
Infrastructure.Components.TableConfig<ViewModels.User.UserViewModel>
_table;*








*    protected override async Task OnInitializedAsync()    {        table =
new();
Infrastructure.Components.AtnBlazor.TableConfig.Config(table);        data
= new ViewPagingDataResult<ViewModels.User.UserViewModel>();        await
loadDataAsync();    }*
*}*



*TableConfig.cs*











*namespace Infrastructure.Components.AtnBlazor{    public static class
TableConfig    {        public static void Config<T>(AntDesign.Table<T>
table)        {            table.Bordered = true;            table.Class =
"table-responsive text-nowrap";        }    }}*

something like above
but it doesn't work ! and I don't know how to create a column in this class
to implement auto increment row
In your first answer you said that I have to configure my class in
RenderFragment<T> for adding new column
Can I do it in this TableConfig class? and how can I do it?

I hope I was able to get what I meant , and thank you for your help in
advance

**Comment by arasheyn** [comment] 2021-05-13 08:55
Hello again
don't you have any suggestions about my previous question?
I really need to find a way to solve that problem
If you could help me I would really appreciate it

Thank you in advance

**Comment by anranruye** [comment] 2021-05-14 13:53
@arasheyn  Ah, I'm not sure I understand what you need. Your previous code is bad-formated and not readable. Can you post a new code fragment to explain your requirement?

**Comment by arasheyn** [comment] 2021-06-07 12:18
Hi , hope you have a good day
How can I make my datagrid responsive?
should I give my table bootstrap class or does it have any properties to do
that?
thanks in advance

**Comment by anranruye** [comment] 2021-06-07 12:45
@arasheyn 

> should I give my table bootstrap class

Don't do that, bootstrap style is not compatible with ant-design style. It's recommended to remove bootstrap totally, or you need to handle the style conflict yourself.

> How can I make my datagrid responsive?

As I know, this is not implemented yet. And you'd better open a new issue rather than asking in this thread.

**Closed** 2022-10-27 11:43 UTC
