### ISSUE TITLE
Lag when typing search text in select control

### ISSUE THREAD

**Issue by ardia** [ant-design-blazor/ant-design-blazor#1965] opened 2021-09-22 09:41 UTC
### Further technical details
- AntDesign Nuget Package version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

**Comment by anddrzejb** [comment] 2021-09-22 10:38
Server side or Wasm?

**Comment by ardia** [comment] 2021-09-22 10:47
Server side. I think the same problem [https://github.com/ant-design-blazor/ant-design-blazor/issues/579](url)

**Comment by anddrzejb** [comment] 2021-09-22 10:49
You have this in local development or on deployed app? If deployed app, can you measure latency?

**Comment by ardia** [comment] 2021-09-22 11:07
In local development is fine. It is in deployed app. latency 200-300 ms

**Comment by anddrzejb** [comment] 2021-09-22 11:34
From what I see we do not have any debounce in there. I was planning to do some work with that (I don't like how debounce is currently behaving in the `Input` component), but I am in the middle of `OverlayTrigger` performance optimization (which should also benefit you, because all work I am currently doing is mostly for server-side). Unless @anranruye decides to take this, I will have a look as soon as I can.

**Comment by anranruye** [comment] 2021-09-22 12:28
@anddrzejb I think I have no idea about this. In my view, this issue is mainly caused by the mechanism of blazor server itself.

**Comment by anddrzejb** [comment] 2021-09-22 12:39
Yeah, it is because of the two-way binding. With very small latency, it may not be noticed, but with higher latency the lag/overwriting occurs. Here is what is happening
User types something in the inbox.
  i. The value is sent through SingnalR to the server, where value is applied to bound property
  i. user continues writing (2nd character)
  ii. diffing algorithm applies value in the bound property to the input - thus resetting it back to the first character

As far as I know, there are 2 approaches to solve this issue - debounce or throttling. However I think there are at least 2 ways to implement debounce. Like I said previously - I planned to have a look at this, even started researching the subject, just haven't had a chance to work on this. I think this issue is another major issue for server-side development. 

This problem though is (as far as I know) a standard problem of all apps written for server side. Maybe some of the libs have already solved this, but if you go vanilla, this issue will hit you.

**Comment by anranruye** [comment] 2021-09-25 10:52
@anddrzejb How are other component libraries performing? Do they have any solution? I don't have a test environment here.

**Comment by anddrzejb** [comment] 2021-09-25 11:32
Mudblazor, BlazorStrap & Blazorise is using debouncing. Matblazor & Radzen seems to be ignoring the issue or I cannot find anything substantial in the area (Matblazor has an open issue where it is suggested to add debouncing). I did not go through their solutions in detail, because I am firmly stuck in `OverlayTrigger` perf optimization. I imagine the ones that are using debouncing most probably face the same issue as we are. I hope to do some more involved tests once I start working on this issue.

**Comment by anranruye** [comment] 2021-09-25 14:25
Well, I'm thinking about if we can skip the rendering of the input component which is active(maybe by making ShouldRender to return false?)(and still render the other parts in the page), then it's possible to avoid to revert the input value to a previous status. Here "active" means the input component is the source who triggered the event. However, there are still troubles when switch the active component. The new active component will still be affected by the event triggered by the previous active component if the latency is large enough.

And I think we should make the issues clear. I often feel we are talking about some different things and mix them together.
We are taking about:
1. latency, for both server side and wasm, caused by different reasons. 
 1.1 for wasm, it's caused by low performance of blazor wasm itself(compared with a local development blazor server app) and too many renders. we can reduce the render times, or we can just wait for the blazor wasm update.
 1.2 for server, it's mainly caused by network quality and we can do nothing for that
2. overwriting, largely because we use blazor server in the wrong way, we should not monitor every keystroke event, just as mousemove event, but we did. I'm afraid there is no perfect solution. Currently it's recommend to only trigger a event callback once the user finish input, which is also not good.

**Comment by anddrzejb** [comment] 2021-09-25 15:04
@anranruye I haven't seen any issues with wasm, so issues you are mentioning are new to me. However I accept they exist and should also be addressed. So previously I was referring only to server-side. In the light of wasm isssues - I agree with your points. 

I am on a kind-of mini crusade to limit number of renderings. I believe unnecessary renderings are a big contributor to performance hit. The problem is that finding the cause of renderings is not always trivial but always time consuming. On top of that, fixes can often increase number of renderings (often unnecessarily). I still hope to find a way to properly benchmark number of renderings and include that info into tests, so they can be stored in a snapshot and fail in case of render count increase.
Now, your suggestion to employ `ShouldRender() ` is interesting and I will test it.
The server side issue & latency - I was wandering how feasible is to internally probe the latency and adjust debouncing/throttle based on connection degradation/strengthening. If this is possible and wont introduce to much overhead, maybe it could solve some of the serverside issues.

Also, we acually should try to have common debouncing/throttling solution, so it can be easily added to any component that has an underlying input element and that can be easily tested.

Your last point - I don't think we should limit input in such a way. Recommend it, sure. But there are scenarios (like async loading for select) when we actually need to monitor for every character (with debounce).

**Comment by anranruye** [comment] 2021-09-25 16:10
@anddrzejb Maybe I am wrong.

The reason I mentioned wasm is that in #579 I saw people said something like:

> I'm taking a guess, but I think the entire form is being re-rendered on every key press -- then the more elements you have, the longer it will lock.

> This behavior is very undesirable. I can confirm that it happens when an Input is embedded in a Form, and the performance issues only seem to exist when wrapped with a FormItem. I suspect it has something to do with validation causing rerender.

> Yes it happens with the built in input control, but the lag is worst when used with FomItem. I think it is related to how complex your container is (how many inputs/elements in the parent container)

I think they are talking about wasm. As I feel, a local blazor server app is much faster than wasm app. For example, for #1911, we can see seconds of ui block for a wasm app, and the latency even grows times when there are more table columns or rows. But for a blazor server app, we can hardly notice the latency. I don't know whether renderings also have so much impact on performance for deployed blazor server apps. If so, please correct me.

Of course, reducing renderings are important for performance, but I think this does more benefit to wasm apps; for server app, it may have little effect, unless there are multiple travel around for **ONE** operation and we can reduce the times(for example, optimize the position calculation for `Overlay`). Again, If I am wrong, please correct me.

------------------------------------------------------------------------------------

Why and when and how should we use blazor server is a huge topic.

The issue for application scenarios of blazor server is very embarrassing. As we know, there are some scenarios that blazor server is naturally not suitable.

Should we only use blazor server with good network environment? Maybe.

Reducing the number of interactions is a solution? Yes.

To what extent? It's hard to say.

Of course we can move all the interactions which should be on the client side to js. But this will make a big gap between the code of blazor server and blazor wasm. And then what is it look like, a reactive MVC? Sounds not bad, but then why we don't use mvc directly? We should give a answer to this question.

**Comment by anddrzejb** [comment] 2021-09-25 16:57
@anranruye It does seem like wasm situation also requires some investigation. We already have different behavior implemented for Wasm/ServerSide, so I do expect such differentiation is going to happen again.

I read multiple times that Wasm is kind-of slow when there are a lot of elements and/or code that requires async. I guess this problem is going to persist as long as wasm stays single threaded. This though should not give us an excuse to not pursue better performance. Regarding multiple renderings - these are wasted cycles. Also, maybe a difference of 1~5 rerenderings is not much, but I don't believe it is meaningless when multiple nested components are involved. I remember I once manage to reduce 29 rerenderings of routed menu component when clicked down to 3 rerenderings. We even had multiple navigation events during these events. It is hard for me to believe this kind of fix had no visible effect. And regarding server-side - multiple renderings may have an impact, especially that js interop can be called separately during each render. Of course it depends, but there is always that kind of threat. And repeated unnecessary js calls in server-side are definitely not welcome.
Another reason to avoid multiple rerenderings - in case of AntBlazor, there are multiple components that use non-primitive parameters. Every rerendering will go through every such parameter. That is another possible performance hit. 

> Why and when and how should we use blazor server is a huge topic.

I don't think it is our place to discuss that. After all, this library is _only_ a UI library. Helping to choose deployment model is really not our job. I mean, there are so many reasons for and against and probably every one has their own arguments for and against. I myself exclusively use server side, mostly because I cannot bare the loading time of Wasm (and historically because of the debugging experience). Also, I only work with enterprise, so either lan of fast internet connection & vpn. The issues with wasm lagging (you mentioned #1911) is not helping here either. So that is why you may see me over-focusing on fixing server-side issues. But I also agree, server side is not for every use. It probably should not be used in public facing sites or when there is a huge lag.

The suggestion of transferring all client side to js - I probably am against that. Even though I was kind-of championing I think first such attempt in AntBlazor (I am talking about transferring `Overlay` repositioning logic fully to js). Unless it is absolutely necessary - I think we should avoid it and rather wait for wasm to get access to DOM. Once that happens, then I believe our options will really open (but @ElderJames will have to release a new package that won't be backward compatible I guess :smirk:). 

Also I am not really clear what do you mean by the code gap between Wasm & Server-side if we start moving client side related code to js. There's no such gap in the `Overlay` works. Can you please elaborate?

**Comment by anranruye** [comment] 2021-09-25 17:56
@anddrzejb our new pr preview site is really much faster than the current .net 5 blazor wasm site(the size is also bigger 😂). Maybe we don't need to worry about wasm performance anymore after .net 6 releases.

The gap I mean, ah, for example form validation, we don't want to validate the form when submit the form(for that case validating on server side is ok), I want to validate as input, if we move the validation logic to js, then we may need to use js to update html dom(display validation message).

Of course we can share same code for blazor server and wasm, but it's unnecessary for wasm to use js to render. However, if we want get validation message immediately, we must use js.

In fact, I'm not sure whether it's good or not to let js invade the render layer. I guess it's not worth it.

**Comment by anddrzejb** [comment] 2021-09-25 18:36
@anranruye You are talking about AOT compiled version of the site? Well, I don't think everyone will switch to AOT, especially when dealing with 2x size. Unless they go to microfront ends, but that is probably even more complex. But even if we abandon perf optimizations in Wasm (which we shouldn't IMHO), there are still a lot of optimizations that are deployment agnostic. So optimizing for server-side will also optimize wasm.

I totally agree we should try to stay away as much as possible from having different paths for Wasm & Server-side. I also generally believe it is dangerous to update dom using js - we face the issue of diverging virtual dom from browser dom. Things may get really weird to debug once that happens.

**Comment by lukblazewicz** [comment] 2022-02-04 07:54
Hey,

Just to bump up the issue - is there any quick hack for this issue (Server-Side)? Can we somehow (on our side) limit the number of items displayed in the overlay to use it as "x top search suggestions only" or maybe enforce virtualization?

The typing lag hits us pretty badly with default behaviour for a few thousand of items.

**Comment by ElderJames** [comment] 2022-02-07 02:56
@lukblazewicz You can limit the number of items displayed in server.

**Comment by lukblazewicz** [comment] 2022-02-07 21:51
@ElderJames Do you mean limiting the number of items in DataSource? Or there is a different solution to keep the total number of items untouched but limit the amount of displayed items in the dropdown list? 

Btw, the solution proposed by @tompru in #2275 also does the trick for us - it would be brilliant to include it in the upcoming release.

**Comment by bobtnt** [comment] 2022-09-12 19:02
> Yeah, it is because of the two-way binding. With very small latency, it may not be noticed, but with higher latency the lag/overwriting occurs. Here is what is happening User types something in the inbox. i. The value is sent through SingnalR to the server, where value is applied to bound property i. user continues writing (2nd character) ii. diffing algorithm applies value in the bound property to the input - thus resetting it back to the first character

The above is exactly the correct problem statement and that's what we should focus on. I'm still facing this issue. Note that the issue cannot be fixed by SearchDebounceMilliseconds nor by limiting number of items to search, because the lag happens during typing, not during search.

Question: any reason why we don't simply implement typing debounce just like the one used in Input component? The DebounceMilliseconds used in Input component works really well for me.

**Comment by ElderJames** [comment] 2022-10-28 06:20
Hi @ardia , @lukblazewicz ,please try the latest 0.12.6 version.

**Comment by ElderJames** [comment] 2024-01-28 16:39
Debounce is default enabled in select now.

**Closed by ElderJames** 2024-01-28 16:39 UTC
Labels: ✉Need feedback
