### ISSUE TITLE
Add  XML documentation for components and their parameters

### ISSUE THREAD

**Issue by truemogician** [ant-design-blazor/ant-design-blazor#1683] opened 2021-06-28 09:13 UTC
## What problem does this feature solve?
Nearly all popular libraries have in-code documentation.  
With XML documentation, developers can get to know the functionality of components and parameters quickly without having to visit the document site and look for them, which could definitely save lots of time for those who are new to Ant Design Blazor.  
Besides, I found quite a few parameters undocumented in the online documentation, leading to difficulty in understanding the usage.

## What does the proposed API look like?
In-code XML documentation migrated from current online documentation

**Comment by anddrzejb** [comment] 2021-06-28 09:29
This is a duplicate of #1495. Currently this is a gradual process. We are slowly adding the xml comments as we go along. Obviously, you are welcome to help in this effort.

**Closed** 2021-06-28 09:30 UTC
Labels: duplicate
