### ISSUE TITLE
Row/Col support error on VS 2022

### ISSUE THREAD

**Issue by wizd** [ant-design-blazor/ant-design-blazor#2132] opened 2021-11-24 09:10 UTC
### Describe the bug

When using Row/Col, VS IDE report:

RZ1034: Found a malformed 'Col' tag helper. Tag helpers must have a start and end tag or be self closing.

![Screenshot 2021-11-24 at 5 09 43 PM](https://user-images.githubusercontent.com/2835415/143208401-1e7b0594-ceb5-4052-84fe-8271f3a7b7aa.png)
### Steps to reproduce (please include code)

        <Row>
            <Col Span="18" Push="6">
                col-18 col-push-6
            </Col>
            <Col Span="6" Pull="18">
                col-6 col-pull-18
            </Col>
        </Row>

### Further technical details
- AntDesign Nuget Package 0.10.2
- Visual Studio Ent. 2022 latest

**Comment by SmRiley** [comment] 2021-11-25 07:33
You can try to use Antdesign.Col (including namespace), there will be no error on my VS2022, but it can't be done.

**Comment by anranruye** [comment] 2021-11-27 09:59
I can't reproduce this either.

**Comment by jeontaejin** [comment] 2021-12-06 09:05
![image](https://user-images.githubusercontent.com/14314108/144817890-cc2c79d6-d05d-4ffa-9353-a0c931e739ab.png)

visual studio 2022
.net core 6.0
If you write row and col in the code block, an error occurs.

**Comment by anranruye** [comment] 2021-12-08 16:02
Got it.

Then the best way to avoid the error is to write the row and col out of a code block if you don't want to use the full name `AntDesign.Col`.  Or you can create a new component class which inherits `AntDesign.Col`.

**Comment by knight1219** [comment] 2021-12-11 16:16
This randomly happens to me as well on VS 2019. Normally I just have to either clean the solution and rebuild, but sometimes this doesn't work.

**Comment by anranruye** [comment] 2021-12-12 07:21
I'm closing this issue because this is caused by vs and .net sdk. We might add a new component with a different name which do the same job. While now you can just create a new class inherits `AntDesign.Col`.

**Closed** 2021-12-12 07:21 UTC
Labels: ✉Need feedback

**Comment by anranruye** [comment] 2021-12-14 03:56
In fact, we already have `GridCol` class which is same as `Col`. And you can it instead.

**Comment by jeontaejin** [comment] 2021-12-14 07:14
> In fact, we already have `GridCol` class which is same as `Col`. And you can use it instead.

thank you.
