### ISSUE TITLE
RangePicker OnChange not executed when value manually entered

### ISSUE THREAD

**Issue by NPadrutt** [ant-design-blazor/ant-design-blazor#1341] opened 2021-04-13 13:01 UTC
### Describe the bug

I have a RangePicker control:

    <RangePicker TValue="DateTime[]" Value="DateRange" OnChange="SelectDateRangeAsync" />

When I select a new range by mouse the OnChange is called as expected. But when I change the value via the KeyBoard it is not'.

### Steps to reproduce (please include code)

1. Click into the start field of a RangePicker
2. Change the value and hit enter
3. Notice that the selection moves to the end field
4. Hit enter again
5. Notice that the OnChange Method is not executed

### Further technical details
- AntDesign Nuget Package version: 0.7.4
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version: VS 16.9.3 / 16.10.0

**Comment by anddrzejb** [comment] 2021-04-16 05:21
This is a dupe of #1324 . It has been fix with #1347 and should be fixed in v.0.8.

**Closed by anddrzejb** 2021-04-16 05:21 UTC
