### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by vertonghenb** [ant-design-blazor/ant-design-blazor#31] opened 2020-03-22 14:06 UTC
Are there any idea's how we will support dark mode? I assume we'll be using a `CascadingParameter` to choose the theme or do you have any other idea's?

**Comment by ElderJames** [comment] 2020-03-22 14:45
For now, any implementation is acceptable.

**Comment by Dorson** [comment] 2020-04-11 01:30
Recently, I coded the Dark Mode switch in CSS and basic Java Script.

In my version of the dark mode, we can have multiple color themes in one CSS file. Then set or remember color settings with one short JS function.

**Try it** on the GitHub demo page :

https://dorson.github.io/CSS-Dark-Mode-and-color-switch/

Feel free to fork, copy, adopt, etc..

Have fun ! :+1:

**Comment by diegofrata** [comment] 2020-08-06 11:07
We are now shipping the original LESS files with the NuGet package which allows user to do their own post-processing and make modifications to either the light/dark theme at build time and run time. So you can go and switch your app to a different theme right now.

As for a dynamic theme selection, we have a couple options here:

1) We can also generate a minified CSS for the dark theme and implement either a top level component or a service for the switch, doing so on a global level (affecting all components, rather than per-component). This is the low hanging fruit and has no dependencies on a custom backend.

2) We can offer a server-side middleware to generate (so that would be built on top of ASP.NET and LigerShark.WebOptimiser) the CSS bundle on the fly -- that's what I use in my apps. With a bit of coding you can even allow the user to override things like @primary-color and have a new CSS bundle generated and loaded.

**Comment by diegofrata** [comment] 2020-08-06 11:50
Sorry after reading a bit more, we could potentially add JSInterop support for using modifyVars in the less.js library as shown in the documentation. I think all approaches can be discussed, the most important thing is that while it's not supported out of the box, anyone using the nightly build can rollout their preferred strategy.

**Comment by ElderJames** [comment] 2020-08-06 13:02
Hi, @diegofrata , can you help implement this feature?

**Comment by Hona** [comment] 2021-01-21 04:09
@diegofrata Using modifyVars at runtime for every user is expensive, it takes about 4 seconds in my testing.

```Dockerfile
# Now compile Ant Design less into CSS with custom theme
FROM node as theme
WORKDIR /theme
COPY --from=build /src/publish/wwwroot/_content/AntDesign/less/ .
COPY ["config/customTheme.less", "customTheme.less"]
RUN npm install less -g
RUN npm install less-plugin-clean-css -g
RUN lessc --clean-css="--s1 --advanced --compatibility=ie8" --js customTheme.less customTheme.css

FROM nginx:alpine
WORKDIR /var/www/web
COPY --from=build /src/publish/wwwroot .
COPY --from=theme /theme/customTheme.css css/customTheme.css
COPY ["Frontend/SharksApp.Frontend.Web/nginx.conf", "/etc/nginx/nginx.conf"]
EXPOSE 80
```

For anyone trying to implement this themselves, I made custom themes in my docker file this way.

customTheme.css:
```less
@import "ant-design-blazor.less";

// Override variables here
@primary-color: #1890ff; // primary color for all components
@link-color: #1890ff; // link color
@success-color: #52c41a; // success state color
@warning-color: #faad14; // warning state color
@error-color: #f5222d; // error state color
@font-size-base: 14px; // major text font size
@heading-color: rgba(0, 0, 0, 0.85); // heading text color
@text-color: rgba(0, 0, 0, 0.65); // major text color
@text-color-secondary: rgba(0, 0, 0, 0.45); // secondary text color
@disabled-color: rgba(0, 0, 0, 0.25); // disable state color
@border-radius-base: 2px; // major border radius
@border-color-base: #d9d9d9; // major border color
@box-shadow-base: 0 3px 6px -4px rgba(0, 0, 0, 0.12), 0 6px 16px 0 rgba(0, 0, 0, 0.08),
0 9px 28px 8px rgba(0, 0, 0, 0.05); // major shadow for layers
```

**Comment by Hona** [comment] 2021-05-18 01:22
Duplicate of #1547

**Comment by ElderJames** [comment] 2021-07-27 17:41
We have built-in dark mode styles now. Just try it in the document site.

**Comment by NPadrutt** [comment] 2021-07-28 05:50
@ElderJames is there a documentation for integrating that in your own page as well? I couldn't find anything on the documentation page and the implementation on the documentation site looks like there are several parts involved including the right files and javascript that has to be called.

**Comment by ElderJames** [comment] 2021-07-28 06:42
@NPadrutt I will explain this in the documentation. 

If you are interested, you can help us write about it, as I am worried that my descriptions are not well understood.

If you want to use the built-in styles, you can refer directly to the corresponding style files.

- Default mode:  /_content/AntDesign/css/ant-design-blazor.css
- Dark mode:  /_content/AntDesign/css/ant-design-blazor.dark.css
- Compact mode: /_content/AntDesign/css/ant-design-blazor.compact.css
- Aliyun mode:  /_content/AntDesign/css/ant-design-blazor.aliyun.css

**Comment by NPadrutt** [comment] 2021-07-28 18:15
oh, that is nice. I'll try that out. If I can make it work in a less hacky way than I have it now with my solution I can try submit a documentation page for it.

**Comment by NPadrutt** [comment] 2021-08-10 12:14
@ElderJames 
can I useone of the built in styles and just replace the primary color?  or would I land then on the "compile the less file yourself" solution?

**Comment by ElderJames** [comment] 2021-08-10 15:16
Use built-in styles is more easy, but that can't change the primary color. User need to compile the less file to change colors.

**Comment by michalss** [comment] 2021-11-01 15:44
Would love to get dark mode, is it up and running on your test site pls ? Or is there a web where i can see it in action pls ?

**Comment by ElderJames** [comment] 2021-11-01 16:48
@michalss Try to import `ant-design-blazor.dark.css`

**Comment by michalss** [comment] 2021-11-01 19:00
> @michalss Try to import `ant-design-blazor.dark.css`

Can you please be more specific ? Where to import, how exactly, where i can get the files, etc ?

**Comment by ElderJames** [comment] 2021-11-02 01:35
Just import it at the head of index.html.
```
<link href="_content/AntDesign/css/ant-design-blazor.dark.css" rel="stylesheet" />
```

**Comment by Hona** [comment] 2021-11-02 03:04
If you want to see how its been done before (with hot switching) - here's one I implemented: https://github.com/AwesomeBlazor/AutoScrum/blob/main/src/AutoScrum/Shared/ThemeProvider.razor

**Comment by michalss** [comment] 2021-11-02 05:44
Thx all ill try, hope this will be implemented directly to AndDesign Blazor package.. :)

**Comment by Hona** [comment] 2021-11-02 05:55
I am planning on implementing my ThemeProvider into AntBlazor natively soon

**Comment by michalss** [comment] 2021-11-02 06:07
> I am planning on implementing my ThemeProvider into AntBlazor natively soon

That would be very nice, how soon ? :)

**Comment by knight1219** [comment] 2021-11-07 23:05
@Hona in your `ThemeProvider` you use the HeadContent component. Isnt that a .net 6 feature? How could we backport this to 3.1. I only ask because I'm currently stuck using 3.1 for the next few month.

**Comment by ElderJames** [comment] 2021-11-08 02:16
We'll be compatible with 3.1 for a while until it's past its end of support(December 03, 2022).

**Closed** 2022-05-11 13:53 UTC
Labels: documentation

**Comment by tammilee18** [comment] 2022-05-26 21:28
@Hona hi! I'm new to blazor wasm and frontend development in general- do you maybe have a repo example that uses docker to compile less for theme customization? If not, could you explain a bit further about how that works? Thanks!
